server:
  port: 9000

# 配置freemarker
spring:
  freemarker:
    template-loader-path: classpath:templates
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    cache: false
  mvc:
    static-path-pattern: /static/**

